#![cfg(feature = "postgres")]

use che_orm::{Database, Model, PostgresBackend};

#[derive(Debug, Clone, Model)]
#[model(table = "che_orm_postgres_query_users")]
struct User {
    #[field(primary_key)]
    id: i64,
    email: String,
    active: Option<bool>,
}

#[tokio::test]
async fn database_query_supports_postgres_predicates_and_count_when_configured() {
    let Some(database_url) = std::env::var_os("CHE_ORM_TEST_POSTGRES_URL") else {
        return;
    };
    let backend = PostgresBackend::connect(database_url.to_str().unwrap())
        .await
        .unwrap();
    sqlx::query("DROP TABLE IF EXISTS che_orm_postgres_query_users")
        .execute(backend.pool())
        .await
        .unwrap();
    sqlx::query(
        "CREATE TABLE che_orm_postgres_query_users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email TEXT NOT NULL, active BOOLEAN)",
    )
    .execute(backend.pool())
    .await
    .unwrap();

    let database = Database::connect(database_url.to_str().unwrap())
        .await
        .unwrap();
    database
        .create::<User>()
        .set(UserFields::EMAIL, "alice@example.com")
        .set(UserFields::ACTIVE, None::<bool>)
        .execute()
        .await
        .unwrap();
    database
        .create::<User>()
        .set(UserFields::EMAIL, "bob@example.com")
        .set(UserFields::ACTIVE, true)
        .execute()
        .await
        .unwrap();

    let user = database
        .query::<User>()
        .filter(
            UserFields::EMAIL
                .contains("alice")
                .and(UserFields::ACTIVE.is_null()),
        )
        .order_by_desc(UserFields::ID)
        .first()
        .await
        .unwrap()
        .unwrap();
    assert_eq!(user.email, "alice@example.com");
    assert_eq!(
        database
            .query::<User>()
            .filter(UserFields::EMAIL.in_values(["alice@example.com", "bob@example.com"]))
            .offset(1)
            .count()
            .await
            .unwrap(),
        2
    );

    sqlx::query("DROP TABLE che_orm_postgres_query_users")
        .execute(backend.pool())
        .await
        .unwrap();
}
