[package]
name = "che-orm-macros"
version = "0.1.0"
edition = "2024"
description = "Procedural macros for che-orm"
license = "MIT"
repository = "https://github.com/che4web/che-orm"
homepage = "https://github.com/che4web/che-orm"
documentation = "https://docs.rs/che-orm-macros"
rust-version = "1.85"
keywords = ["orm", "sqlite", "database"]
categories = ["database"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
proc-macro-crate = "3"
quote = "1"
syn = { version = "2", features = ["derive", "parsing"] }
