use std::marker::PhantomData;

#[cfg(feature = "sqlite")]
use crate::ModelManager;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FieldType {
    Integer,
    Text,
    Boolean,
    Real,
    DateTime,
    Json,
    Choice,
    FilePath,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum ForeignKeyAction {
    #[default]
    NoAction,
    Restrict,
    Cascade,
    SetNull,
    SetDefault,
}

#[derive(Debug, Clone, Copy)]
pub struct ForeignKeyInfo {
    pub table: &'static str,
    pub on_delete: ForeignKeyAction,
}

#[derive(Debug, Clone, Copy)]
pub struct FieldInfo {
    pub rust_name: &'static str,
    pub db_name: &'static str,
    pub ty: FieldType,
    pub primary_key: bool,
    pub nullable: bool,
    pub auto: bool,
    pub unique: bool,
    pub index: bool,
    pub max_length: Option<u32>,
    pub default: Option<&'static str>,
    pub auto_now_add: bool,
    pub auto_now: bool,
    pub foreign_key: Option<ForeignKeyInfo>,
    pub choices: Option<&'static [&'static str]>,
}

pub trait Choice: Sized + Clone + Send + Sync + 'static {
    fn as_str(&self) -> &'static str;
    fn from_str(value: &str) -> Result<Self, String>;
    fn values() -> &'static [&'static str];
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ModelField<M, T> {
    db_name: &'static str,
    _model: PhantomData<fn() -> (M, T)>,
}

impl<M, T> ModelField<M, T> {
    /// Creates a field descriptor for generated ORM code.
    ///
    /// The caller must ensure that `db_name` and `T` describe the same model
    /// field. Prefer the constants generated by `#[derive(Model)]`.
    #[doc(hidden)]
    pub const unsafe fn new(db_name: &'static str) -> Self {
        Self {
            db_name,
            _model: PhantomData,
        }
    }

    pub const fn db_name(&self) -> &'static str {
        self.db_name
    }
}

#[cfg(feature = "sqlite")]
pub trait QueryValue<T> {
    fn into_query_value(self) -> SqliteValue;
}

#[cfg(feature = "sqlite")]
pub trait AggregateValue:
    Sized + Send + Unpin + for<'q> sqlx::Decode<'q, sqlx::Sqlite> + sqlx::Type<sqlx::Sqlite>
{
}

#[cfg(feature = "sqlite")]
impl<T> AggregateValue for T where
    T: Sized + Send + Unpin + for<'q> sqlx::Decode<'q, sqlx::Sqlite> + sqlx::Type<sqlx::Sqlite>
{
}

#[cfg(feature = "sqlite")]
macro_rules! query_value_impl {
    ($field_type:ty, $($value_type:ty),+ $(,)?) => {
        $(impl QueryValue<$field_type> for $value_type {
            fn into_query_value(self) -> SqliteValue {
                self.into()
            }
        })+
    };
}

#[cfg(feature = "sqlite")]
query_value_impl!(i64, i64, i32, u32);
#[cfg(feature = "sqlite")]
query_value_impl!(i32, i32);
#[cfg(feature = "sqlite")]
query_value_impl!(u32, u32);
#[cfg(feature = "sqlite")]
query_value_impl!(String, String, &str);
#[cfg(feature = "sqlite")]
query_value_impl!(bool, bool);
#[cfg(feature = "sqlite")]
query_value_impl!(f64, f64, f32);
#[cfg(feature = "sqlite")]
query_value_impl!(f32, f32);
#[cfg(feature = "sqlite")]
query_value_impl!(chrono::NaiveDateTime, chrono::NaiveDateTime);
#[cfg(feature = "sqlite")]
query_value_impl!(serde_json::Value, serde_json::Value);
#[cfg(feature = "sqlite")]
query_value_impl!(crate::FilePath, crate::FilePath);

#[derive(Debug, Clone)]
pub enum DatabaseValue {
    I64(i64),
    String(String),
    Bool(bool),
    F64(f64),
    DateTime(chrono::NaiveDateTime),
    Json(serde_json::Value),
    Null,
}

#[cfg(feature = "sqlite")]
pub type SqliteValue = DatabaseValue;

impl From<i64> for DatabaseValue {
    fn from(value: i64) -> Self {
        Self::I64(value)
    }
}

impl From<i32> for DatabaseValue {
    fn from(value: i32) -> Self {
        Self::I64(value.into())
    }
}

impl From<u32> for DatabaseValue {
    fn from(value: u32) -> Self {
        Self::I64(value.into())
    }
}

impl From<String> for DatabaseValue {
    fn from(value: String) -> Self {
        Self::String(value)
    }
}

impl From<&str> for DatabaseValue {
    fn from(value: &str) -> Self {
        Self::String(value.to_string())
    }
}

impl From<bool> for DatabaseValue {
    fn from(value: bool) -> Self {
        Self::Bool(value)
    }
}

impl From<f64> for DatabaseValue {
    fn from(value: f64) -> Self {
        Self::F64(value)
    }
}

impl From<f32> for DatabaseValue {
    fn from(value: f32) -> Self {
        Self::F64(value.into())
    }
}

impl From<chrono::NaiveDateTime> for DatabaseValue {
    fn from(value: chrono::NaiveDateTime) -> Self {
        Self::DateTime(value)
    }
}

impl From<serde_json::Value> for DatabaseValue {
    fn from(value: serde_json::Value) -> Self {
        Self::Json(value)
    }
}

impl From<crate::FilePath> for DatabaseValue {
    fn from(value: crate::FilePath) -> Self {
        Self::String(value.into_inner())
    }
}

pub trait Model: Sized + Send + Sync + 'static {
    type Id: Clone + Send + Sync + Into<i64>;
    type Update: Send + Sync;

    fn table_name() -> &'static str;
    fn fields() -> &'static [FieldInfo];

    fn primary_key() -> Option<&'static FieldInfo> {
        Self::fields().iter().find(|field| field.primary_key)
    }

    #[cfg(feature = "sqlite")]
    fn objects(db: &crate::SqliteBackend) -> ModelManager<'_, Self>
    where
        Self: SqliteModel,
    {
        ModelManager::new(db)
    }

    #[cfg(feature = "postgres")]
    fn postgres_objects(db: &crate::PostgresBackend) -> crate::PostgresModelManager<'_, Self>
    where
        Self: PostgresModel,
    {
        crate::PostgresModelManager::new(db)
    }

    fn get_value(&self, _field: &str) -> Option<crate::__private::serde_json::Value> {
        None
    }
}

#[cfg(feature = "sqlite")]
pub trait SqliteModel: Model {
    fn from_row(row: &sqlx::sqlite::SqliteRow) -> sqlx::Result<Self>;
    fn id(&self) -> Self::Id;
    fn update_values(data: Self::Update) -> Vec<(&'static str, SqliteValue)>;
    fn save_values(&self) -> Vec<(&'static str, SqliteValue)>;
}

#[cfg(feature = "postgres")]
pub trait PostgresModel: Model {
    fn from_postgres_row(row: &sqlx::postgres::PgRow) -> sqlx::Result<Self>;
    fn id(&self) -> Self::Id;
    fn update_values(data: Self::Update) -> Vec<(&'static str, DatabaseValue)>;
    fn save_values(&self) -> Vec<(&'static str, DatabaseValue)>;
}
