[package]
name = "che-orm-examples"
version = "0.2.0"
edition = "2024"
publish = false

[features]
default = ["sqlite"]
sqlite = []

[dependencies]
orm = { package = "che-orm", path = ".." }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
time = { version = "0.3", features = ["formatting", "parsing"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
