use crate::models::User;
use crate::{
    ColumnRef, DatabaseValue, Model, PostgresDialect, QueryBuildError, SqlCompiler, SqliteDialect,
};

#[test]
fn derive_model_defines_consistent_metadata() {
    assert_eq!(User::table_name(), "users");
    assert_eq!(
        User::columns(),
        [
            "id",
            "email",
            "name",
            "is_active",
            "created_at",
            "updated_at"
        ]
    );
    assert_eq!(User::NAME.column(), ColumnRef::new("users", "name"));
}

#[test]
fn compiles_select_with_sqlite_parameters() {
    let query = User::query()
        .filter(User::ID.gt(10).and(User::IS_ACTIVE.eq(true)))
        .order_by(User::NAME.asc())
        .limit(20)
        .offset(5)
        .into_ast()
        .unwrap();
    let compiled = SqlCompiler::<SqliteDialect>::compile(&query);
    assert_eq!(
        compiled.sql,
        "SELECT users.id, users.email, users.name, users.is_active, users.created_at, users.updated_at FROM users WHERE ((users.id > ?) AND (users.is_active = ?)) ORDER BY users.name ASC LIMIT 20 OFFSET 5"
    );
    assert_eq!(
        compiled.params,
        vec![DatabaseValue::Integer(10), DatabaseValue::Boolean(true)]
    );
}

#[test]
fn compiles_insert_with_postgres_parameters() {
    let query = User::insert()
        .set(User::EMAIL, "alice@example.test")
        .set(User::NAME, "Alice")
        .returning_all()
        .into_ast()
        .unwrap();
    let compiled = SqlCompiler::<PostgresDialect>::compile(&query);
    assert_eq!(
        compiled.sql,
        "INSERT INTO users (email, name) VALUES ($1, $2) RETURNING id, email, name, is_active, created_at, updated_at"
    );
    assert_eq!(
        compiled.params,
        vec![
            DatabaseValue::Text("alice@example.test".into()),
            DatabaseValue::Text("Alice".into())
        ]
    );
}

#[test]
fn rejects_invalid_mutating_queries() {
    assert_eq!(
        User::insert().into_ast().unwrap_err(),
        QueryBuildError::EmptyInsert
    );
    assert_eq!(
        User::update().into_ast().unwrap_err(),
        QueryBuildError::EmptyUpdate
    );
    assert_eq!(
        User::update()
            .set(User::NAME, "Alice")
            .into_ast()
            .unwrap_err(),
        QueryBuildError::MissingFilter
    );
    assert_eq!(
        User::delete().into_ast().unwrap_err(),
        QueryBuildError::MissingFilter
    );
    assert_eq!(
        User::insert()
            .set(User::NAME, "Alice")
            .set(User::NAME, "Bob")
            .into_ast()
            .unwrap_err(),
        QueryBuildError::DuplicateColumn("name")
    );
}

#[test]
fn compiles_sqlite_create_table_from_model() {
    let compiled = SqlCompiler::<SqliteDialect>::compile(&User::create_table().into_ast());
    let schema = SqlCompiler::<SqliteDialect>::compile_schema(&User::schema());

    assert_eq!(
        compiled.sql,
        "CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL CHECK (length(name) > 0), is_active INTEGER NOT NULL DEFAULT true, created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now')), updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%f', 'now')), UNIQUE (email))"
    );
    assert_eq!(
        schema.indexes,
        vec!["CREATE INDEX users_idx_0 ON users (name)"]
    );
    assert_eq!(
        schema.triggers,
        vec![
            "CREATE TRIGGER users_updated_at_auto_update AFTER UPDATE ON users FOR EACH ROW WHEN NEW.updated_at = OLD.updated_at BEGIN UPDATE users SET updated_at = (strftime('%Y-%m-%d %H:%M:%f', 'now')) WHERE rowid = OLD.rowid; END"
        ]
    );
}

#[test]
fn compiles_postgres_identity_create_table_from_model() {
    let compiled = SqlCompiler::<PostgresDialect>::compile(&User::create_table().into_ast());

    assert_eq!(
        compiled.sql,
        "CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL CHECK (length(name) > 0), is_active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE (email))"
    );
}

#[cfg(feature = "sqlite")]
#[tokio::test]
async fn sqlite_pool_persists_and_loads_models() {
    let path = std::env::temp_dir().join(format!("che_orm2_test_{}_{}.db", std::process::id(), 1));
    let _ = std::fs::remove_file(&path);

    let database = crate::Database::connect(path.to_string_lossy().into_owned()).unwrap();
    database.create_table::<User>().await.unwrap();

    let user = User {
        id: 0,
        email: "alice@example.test".into(),
        name: "Alice".into(),
        is_active: true,
        created_at: time::OffsetDateTime::now_utc(),
        updated_at: time::OffsetDateTime::now_utc(),
    };
    let result = database.insert(&user).await.unwrap();
    assert_eq!(result.rows_affected, 1);
    assert!(result.last_insert_rowid.unwrap() > 0);

    let loaded = database
        .fetch_one(User::query().filter(User::EMAIL.eq("alice@example.test")))
        .await
        .unwrap()
        .unwrap();
    assert_eq!(loaded.email, user.email);
    assert_eq!(loaded.name, user.name);
    assert!(loaded.is_active);

    let previous_updated_at = loaded.updated_at;
    std::thread::sleep(std::time::Duration::from_millis(2));
    database
        .execute(
            User::update()
                .set(User::NAME, "Updated Alice")
                .filter(User::EMAIL.eq("alice@example.test"))
                .into_ast()
                .unwrap(),
        )
        .await
        .unwrap();
    let updated = database
        .fetch_one(User::query().filter(User::EMAIL.eq("alice@example.test")))
        .await
        .unwrap()
        .unwrap();
    assert!(updated.updated_at > previous_updated_at);
    assert_eq!(updated.name, "Updated Alice");

    let _ = std::fs::remove_file(path);
}
